# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo/uclusion_sdk

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: cd uclusion_sdk/ && npm test
      
      # checkout nodejs_sdk repo
      - checkout:
          path: ~/repo/nodejs_sdk
          
      - run:
          name: debugging
          command: |
            pwd
            ls -l
            ls -l ~/repo/
            ls -l ~/repo/uclusion_sdk/
            ls -l ~/repo/nodejs_sdk/
            
