# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:69:2a:ea:79:a8:a2:7a:7f:90:3c:06:9f:52:db:e5"
    
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
        
      - run:
          name: Run unit tests
          command: npm test
          when: always
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run:
          name: Generate code coverage
          command: npm run coverage
          when: always
      
      - store_artifacts:
          path: test/mocha/test-results.xml
          prefix: tests
          
      - store_artifacts:
          path: test/coverage
          prefix: coverage
          
      - store_test_results:
          path: test
      
      - run:
          name: Check out nodejs_sdk repo
          command: |
            cd ~/
            mkdir nodejs_sdk_repo
            git clone git@github.com:Uclusion/nodejs_sdk.git ./nodejs_sdk_repo
      
      - run:
          name: Create link for uclusion_sdk dependency
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm link ../repo
            
      - run:
          name: Run integration tests
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm test
            
      - run:
          name: Generate code coverage
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm run coverage
          
      - store_artifacts:
          path: ~/nodejs_sdk_repo/test/nodejs/test-results.xml
          prefix: tests
          
      - store_artifacts:
          path: ~/nodejs_sdk_repo/test/coverage
          prefix: coverage    
          
      - store_test_results:
          path: ~/nodejs_sdk_repo/test

      - persist_to_workspace:
          root: ~/repo
          paths: .
          
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
          
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            
      - run:
          name: Publish package
          command: npm publish

workflows:
  build-deploy:
    jobs:
      - build:
          filters: # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
              
