# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:69:2a:ea:79:a8:a2:7a:7f:90:3c:06:9f:52:db:e5"
    
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm install mocha-junit-reporter # just for CircleCI
      
      - run: npm install nyc

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}  
        
      - run: mkdir reports  
        
      # Run mocha
      - run:
          name: npm test
          command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha --recursive --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
          when: always
      
      # Upload results
      - store_test_results:
          path: reports

      - store_artifacts:
          path: ./reports/mocha/test-results.xml
      
      - run:
          name: checking out nodejs_sdk repo
          command: |
            cd ~/
            mkdir nodejs_sdk_repo
            git clone git@github.com:Uclusion/nodejs_sdk.git ./nodejs_sdk_repo
      
      - run:
          name: updating nodejs_sdk local dependencies
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm link ../repo
            
      - run:
          name: running nodejs_sdk tests
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm test
          
