# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:69:2a:ea:79:a8:a2:7a:7f:90:3c:06:9f:52:db:e5"
    
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: run unit tests
          command: npm test
          when: always
          
      - run:
          name: generate code coverage
          command: npm run coverage
          when: always
      
      - store_artifacts:
          path: test/mocha/test-results.xml
          prefix: tests
          
      - store_artifacts:
          path: test/coverage
          prefix: coverage
          
      - store_test_results:
          path: test
      
      - run:
          name: check out nodejs_sdk repo
          command: |
            cd ~/
            mkdir nodejs_sdk_repo
            git clone git@github.com:Uclusion/nodejs_sdk.git ./nodejs_sdk_repo
      
      - run:
          name: update nodejs_sdk local dependencies
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm link ../repo
            
      - run:
          name: run integration tests
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm test
            
      - run:
          name: generate code coverage
          command: |
            cd ~/nodejs_sdk_repo
            sudo npm run coverage
          
      - store_artifacts:
          path: ~/nodejs_sdk_repo/test/nodejs/test-results.xml
          prefix: tests
          
      - store_artifacts:
          path: ~/nodejs_sdk_repo/test/coverage
          prefix: coverage    
          
      - store_test_results:
          path: ~/nodejs_sdk_repo/test
          
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
            
      - run:
          name: Publish package
          command: |
            npm config ls -l
            npm publish --userconfig ~/.npmrc
            
